# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: balancer-loxilb
# spec:
#   selector:
#     matchLabels:
#       app: loxilb
#   template:
#     metadata:
#       labels:
#         app: loxilb
#       annotations:
#         k8s.v1.cni.cncf.io/networks: '[
#           { "name": "n2network", "interface": "n2", "ips": [ "10.10.2.1/24" ] }
#           ]'
#     spec:
#       initContainers:
#       - name: wait-amf
#         image: busybox:1.32.0
#         env:
#         - name: DEPENDENCIES
#           value: amf-namf:8000
#         command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the AMF; sleep 2; done;"]
#       - name: wait-amf2
#         image: busybox:1.32.0
#         env:
#         - name: DEPENDENCIES
#           value: amf2-namf:8000
#         command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the AMF2; sleep 2; done;"]
#       containers:
#       - name: lb
#         image: ghcr.io/loxilb-io/loxilb:latestu22
#         command: ["loxicmd", "create", "lb", "20.20.20.1", "--sctp=38412:38412", "--endpoints=10.10.2.2:1,10.10.2.3:1", "--mode=onearm"]
#         securityContext:
#           privileged: true
#           capabilities:
#             add:
#               - SYS_ADMIN
#               - NET_ADMIN
#         ports:
#         - containerPort: 38412
#           protocol: SCTP
#       restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: loxilb
  labels:
    app: loxilb
spec:
  ports:
  - port: 8091
    name: restapi-one
  - port: 11111
    name: restapi-two    
  # clusterIP: None
  selector:
    app: loxilb
---    
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loxilb
  labels:
    app: loxilb
spec:
  serviceName: loxilb
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: loxilb
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "n2network", "interface": "n2", "ips": [ "10.10.2.1/24" ] }
          ]'
      labels:
        app: loxilb
    spec:   
      initContainers:
      - name: wait-amf
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: amf-namf:8000
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the AMF; sleep 2; done;"]
      - name: wait-amf2
        image: busybox:1.32.0
        env:
        - name: DEPENDENCIES
          value: amf2-namf:8000
        command: ["sh", "-c", "until nc -z $DEPENDENCIES; do echo waiting for the AMF2; sleep 2; done;"]     
      containers:
      - name: loxilb
        image: ghcr.io/loxilb-io/loxilb:latest
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh","-c","sleep 10; for i in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > $i; done; loxicmd create lb 10.10.2.1 --sctp=38412:38412 --endpoints=10.10.2.2:1,10.10.2.3:1 --mode=onearm" ]
        ports:
        - containerPort: 8091
          name: restapi-one
        - containerPort: 11111
          name: restapi-two           
        securityContext:
          privileged: true